[Controls]
Style=RezManager.DarkRezStyle
FallbackStyle=Fusion

[RezManager.DarkRezStyle]
Palette\Window=#0E0E16
Palette\WindowText=#E8EAFA
Palette\Base=#13131E
Palette\AlternateBase=#1A1A28
Palette\Text=#E8EAFA
Palette\Button=#1A1A28
Palette\ButtonText=#E8EAFA
Palette\Highlight=#5F83FF
Palette\HighlightedText=#FFFFFF
Palette\PlaceholderText=#9090B8
Palette\ToolTipBase=#1A1A28
Palette\ToolTipText=#E8EAFA
